server:
  port: 8081

spring:
  application:
    name: account-service
  data:
    cassandra:
      keyspace:
        name: springcloud
      contact:
        point: 127.0.0.1
      port: 9042
      schema-action: create_if_not_exists
      username: cassandra
      password: cassandra
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8500}
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      account:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
#Resilience4j Timeout Properties
  timelimiter:
    instances:
      account:
        timeout-duration: 3s
#Resilience4j Retry Properties
  retry:
    instances:
      account:
        max-attempts: 3
        wait-duration: 5s