server:
  port: 8083

spring:
  application:
    name: notification-service
  rabbitmq:
    username: rabbit
    password: rabbit
  cloud:
    stream:
      bindings:
        input:
          destination: queues
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8500}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost