version: '3.1'

services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
  elasticsearch:
    image: arm64v8/elasticsearch:7.17.17
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit